# frozen_string_literal: true

module ViewComponent
  module ScopedStyles
    class Stylist
      class Writer
        def self.print(component_class)
          new.print!(component_class)
        end

        def print!(component_class)
          component_name = component_class.name
          component_class.instance_variable_get(:@component_id)
          styles = component_class.component_styles

          ensure_stylesheet_exists!

          update_stylesheet_with(component_name, styles)
        end

        private

        def ensure_stylesheet_exists!
          return if File.exist?(stylesheet_path)

          FileUtils.mkdir_p(File.dirname(stylesheet_path))
          File.write(stylesheet_path, initial_content)
        end

        def update_stylesheet_with(component_name, styles)
          content = File.read(stylesheet_path)
          updated_content = merge_styles_into(content, component_name, styles)

          write_atomically(updated_content)

          notify_asset_pipeline!
        end

        def merge_styles_into(content, component_name, styles)
          wrapped_styles = wrap_with(component_name, styles)
          pattern = style_pattern_for(component_name)

          if content.match?(pattern)
            content.gsub(pattern, wrapped_styles.strip)
          else
            append_styles_to(content, wrapped_styles)
          end
        end

        def write_atomically(content)
          if ViewComponent::ScopedStyles.configuration.components_layer
            content = content.rstrip + "\n}\n"
          end

          temp_file = generate_temp_file_name

          File.write(temp_file, content)
          FileUtils.mv(temp_file, stylesheet_path)
        end

        # Multiple Rails processes can boot concurrently (e.g. web + jobs),
        # so each writer needs its own temp file to avoid rename races.
        def generate_temp_file_name
          "#{stylesheet_path}.#{Process.pid}.#{Thread.current.object_id}.#{Process.clock_gettime(Process::CLOCK_MONOTONIC, :nanosecond)}.tmp"
        end

        def notify_asset_pipeline! = FileUtils.touch(stylesheet_path)

        def wrap_with(component_name, styles)
          start_marker = "/* #{component_name} */\n"
          end_marker = "/* /#{component_name} */"

          "#{start_marker}#{styles}#{end_marker}"
        end

        def style_pattern_for(component_name)
          /\/\* #{Regexp.escape(component_name)} \*\/\n.*?\/\* \/#{Regexp.escape(component_name)} \*\//m
        end

        def append_styles_to(content, wrapped_styles)
          [content.chomp, wrapped_styles, "\n"].join("\n")
        end

        def initial_content
          content = "/* Generated by ViewComponent::ScopedStyles - Do not edit manually */\n"

          if (layer = ViewComponent::ScopedStyles.configuration.components_layer)
            content += "@layer #{layer} {\n"
          end

          content
        end

        def stylesheet_path
          @stylesheet_path ||= Rails.root.join("app/assets/stylesheets/components.scoped.css")
        end
      end
    end
  end
end
